# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_missions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_cat',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
